var := Software
new := Tmzhou
test : var := T1mzhou
%e : override new := test-new

test : another
	@echo "test :"
	@echo "var => $(var)"
	@echo "new => $(new)"

another :
	@echo "another :"
	@echo "var => $(var)"
	@echo "new => $(new)"
rule :
	@echo "rule :"
	@echo "var => $(var)"
	@echo "new => $(new)"
